### ISSUE TITLE
Find task should have a `depth` argument

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#10]
The `find` task should be able to limit the recursive search to a maximum depth, as in
```yaml
- find:
    path: .
    depth: 3
- echo:
    msg: "Found file: {{item}}"
  loop: "{{result}}"
```
which should print all files down to three subdirectory levels from the current directory.
