### ISSUE TITLE
Define a sequence for a loop

### ISSUE THREAD

**Issue by oloapinivad** [uwefladrich/scriptengine#107]
Is there a way to define a sequece into a loop? 

The structure below works pretty well:
```
- base.echo: 
    msg: "I have {{mouse}} mouses in my office."
  loop: 
    with: mouse
    in: [0, 1, 2, 4, 5]
```

But what if I want to define the amount of loops only? I would expect something like this to work building on python

```
- base.context:
    mouses: 5

- base.echo: 
    msg: "I have {{mouse}} mouses in my office."
  loop: 
    with: mouse
    in: range(0, {{mouses}}
```

How can I achieve the same result with ScriptEngine? 
Thanks?

**Comment by oloapinivad** [comment]
Aaaaaah I see I need to work with jinja instead of python.
 
Do you it is possible with the current structure ScriptEngine to define in the future "extensions" or "aliases" so that we can simplify jinja commands into something more user-friendly? I mean, in the long term I think the more we can extend and collaborare in the development of SE the better will be also for ECE4. 

PS
thanks for spotting the grammar error :-)

**Comment by uwefladrich** [comment]
Before addressing the "extensions" question (I'll put that in another comment), let me propose another version of the mice code, which may structure the code a bit better and make it, in a way, more "user-friendly":

```yaml
 base.context:
    population: 13
    mice: !noparse "[{% for k in range(population) %}{{k+1}},{% endfor %}]"

# ... later ...

- base.echo:
    msg: "Hello, this is mouse no. {{item}}!"
  loop: "{{mice}}"
```

That does not make the Jinja expression disappear, but it makes the _loop_ code a lot cleaner and puts the complexity on the spot where it is needed, i.e. creating the list of mice. Moreover, one can reuse the mice list.

**Comment by uwefladrich** [comment]
... I was about to write a longer comment, when a thought struck me:
```yaml
- base.echo:
    msg: "Hello, this is mouse no. {{item}}!"
  loop: "{{range(5)|list}}
```
I guess that this version meets the simplicity criterion?

It also proves the point I was going to make anyway: one of the fundamental principles of ScriptEngine is to rely on YAML and Jinja. All the heavy lifting to parse the scripts is done there. And I always found (so far) that it pays off to keep the extra rules on syntax (i.e. the SE specific part) as small as possible. It is much easier to code (SE is not a huge code base), maintain, document, and learn.

So this example illustrates that using the potential of Jinja is better than coding for extra syntax. This being said, there are exceptions. There are a couple of extra Jinja filtes, that SE defines and that extend the Jinja language (`string_to_datetime`, `string_to_date`, `basename`, `dirname`, `exists`, `path_join`). Adding new (SE specific) Jinja filters is easily coded and they follow the general Jinja syntax, so they are easy to understand.

And I also admit that following the YAML+Jinja-only approach does introduce some limitations. But so far I think the advantages outweigh the limitations.
