### ISSUE TITLE
Force parsing of `!noparse` string when evaluating a string

### ISSUE THREAD

**Issue by oloapinivad** [uwefladrich/scriptengine#121]
I have noticed that, as in the example below, if a string is defined with the `!noparse` statement, is then impossible to force its parsing in a later usage but I have to define a new context to get it correctly parsed. Operations as `when` (but I guess anything else) will not work as expected since the string is still unparsed. 

```yaml
- base.context:
    pub:
      id: 'beer'
      run_dir: !noparse "love/my/{{id}}"
    
- base.context:
    eval_dir: "{{ pub.run_dir }}"

- base.make_dir:
    path: "{{ eval_dir }}"

- when: '{{ eval_dir | exists }}'
  base.echo:
    msg: "Parsed {{ pub.run_dir}}"
```

This example above will print `Parsed love/my/` and ignore the `beer` argument unless I call `eval_dir`. I am aware this is the idea behind the `!noparse` syntax but there situations where it might be useful to force the parsing. Is there a way to force the parsing, something as  "Parsed {{ pub.run_dir}} | parse" so that the statement is correctly evaluated and can be used directly?

**Comment by plesager** [comment]
See also [this EC-Eearth 4 real life example](https://git.smhi.se/sager/ecearth4/-/commit/e2a9f3d4625c0f5b207f85b591166f70681203f1#note_74155).

**Comment by oloapinivad** [comment]
Yes, of course I made it wrong 😞 

```yaml
- base.context:
    pub:
      id: 'beer'
      run_dir: !noparse "love/my/{{pub.id}}"
    
- base.context:
    eval_dir: "{{ pub.run_dir }}"

- base.make_dir:
    path: "{{ eval_dir }}"

- when: '{{ eval_dir | exists }}'
  base.echo:
    msg: "Parsed {{ pub.run_dir}}"

- when: '{{ pub.run_dir | exists }}'
  base.echo:
    msg: "Not parsed {{ pub.run_dir}}"
```

this should be better
