### ISSUE TITLE
Implement `time` base task

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#13]
Like:
```yaml
- time:
    set: <context_var>
```
or
```yaml
- time:
    since: <datetime>
    set: <context_var>
```
