### ISSUE TITLE
Nested tasked arguments not parsed

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#15]
When task arguments are dictionaries, they are not parsed by `Task.getarg()` as they should. This is different from nested lists. Example:
```yaml
- context:
    world: earth

- command:
    name: echo
    args:
        - Hello:
            planet: "{{world}}"
```
yields:
```
{'Hello': {'planet': '{{world}}'}}
```
i.e. `{{world}}` is not parsed.
