### ISSUE TITLE
Review task timing implementation

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#22]
Task timing in SE needs two parts:

1. Task classes need to have their `run()` methods decorated with `timed_runner` from `tasks.base.timing`,
2. Task timing needs to be configured at run time with the `task_timer` task.

Things could be simplified:

* Task timing could be mandatory (at the instance level) and with default options, so no need for configuration with `task_timer`.
* The base class `Task` could have a `Task.timed_run()` method, which calls `Task.run()` with timing. Hence, task developers would not need to decorate their `run()` methods manually.

**Comment by uwefladrich** [comment]
Possible set of default options:
```yaml
task_timer:
    mode: instance
    set: _se.tasks.timer
    logging: debug
```
