### ISSUE TITLE
When clause with empty/undefined expression

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#33]
Similar to #8, just for `when` instead for `loop`. Consider
```yaml
base.echo:
    msg: "Foo. Bar!"
when: "{{foo}}"
```
which will result in an exception that is not handled.
