### ISSUE TITLE
base.copy handles missing files incorrectly

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#38]
Assuming
```yaml
base.copy:
    src: foo
    dst: bar
```
and assuming further that `foo` does not exist, the `base.copy` task falsely assumes that `foo` is a directory. It will also raise an unhandled `FileNotFoundError` (appropriate error, but for the wrong reason).
