### ISSUE TITLE
Handling environment variables

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#40]
Two extensions are proposed to handle environment variables, beyond what is possible at the moment with `base.getenv`:

1. set environment variables
1. get/set more than one variable with one task

The get and set tasks should be "symmetric".

**Comment by uwefladrich** [comment]
Proposed YAML syntax for setting environment variables:
```yaml
base.setenv:
    foo: one
    bar: two
    baz: 3
```
which sets the environment variables `foo`, `bar`, `baz` to the respective value. Note that all values are converted to strings (environment variables are always strings).

And for getting variables:
```yaml
base.getenv:
    home: HOME
    user: USER
    shell: SHELL
```
which sets the context parameters `home`, `user`, `shell` from the environment variables `$HOME`, `$USER`, `$SHELL`, respectively.
