### ISSUE TITLE
Make sure keys from YAML are strings

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#5]
This:
```yaml
- config:
    no: foo
- echo:
    msg: "{{no}}"
```
yields:
```
TypeError: keyword arguments must be strings
```
because `no` is considered `False` in the YAML context.

**Comment by uwefladrich** [comment]
Check if this is only needed for the `config` task, i.e. making sure that config parameter names are strings. Decide if an automatic conversion or a check+error is preferable. See above example in issue description!

**Comment by uwefladrich** [comment]
This is solved for the `config` task with 25e1dc41a89dcf539dde90ba68fb174207a47658.

**Comment by uwefladrich** [comment]
For example:
```yaml
- echo:
    msg: Hi!
    2: 4
````
works fine, despite the extra parameter with `int` type. Closing the issue for now because it is not clear that this is a problem.
