### ISSUE TITLE
Looping over list of dicts doesn't work in particular case

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#53]
There is a particular case where looping over a list of dicts does not work:
```yaml
- base.context:
    list:
      - foo:
          bar: 1
          baz: 2
      - foo:
          bar: 3
          baz: 4
- base.echo:
    msg: '{{item.foo.bar}} - {{item.foo.baz}}'
  loop: "{{list}}"
```
This raises a `jinja2.exceptions.UndefinedError: 'str object' has no attribute 'config'`
