### ISSUE TITLE
base.include messes up the context

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#55]
A new bug has been introduced that causes the `include` task to change the context erroneously:
```yaml
- base.context:
    foo: [1, 2]
- base.echo:
    msg: 'Before include, foo is {{foo}}'
- base.include:
    src: include.yml  # any included script, even without context access
- base.echo:
    msg: 'After include, foo is {{foo}}'
```
`foo` from the context is `[1, 2]` before the include task and `[1, 2, 1, 2]` after.
