### ISSUE TITLE
loop on strings tuple not working as expected

### ISSUE THREAD

**Issue by oloapinivad** [uwefladrich/scriptengine#59]
I have experienced an issue when looping on string tuples. 

```
# Deactivate copying of coupling weights, compute on-the-fly only for AMIP

base.echo:
  msg: "rmp_{{item[0]}}_to_{{item[1]}}_{{item[2]}}.nc"
loop:
    - [IOCL, NOTM, GAUSWGT]
    - [IOCL, NOUM, GAUSWGT]
    - [IOCL, NOVM, GAUSWGT]
    - [NOTM, IOCL, GAUSWGT]
 ```

But the looping is not working as expected: 
```
2022-02-10 09:43:13 INFO [se.cli] Logging configured and started
2022-02-10 09:43:13 INFO [se.task:echo <99b7d264dc>] rmp_{{item[0]}}...
rmp_I_to_O_C.nc
2022-02-10 09:43:13 INFO [se.task:echo <99b7d264dc>] rmp_{{item[0]}}...
rmp_I_to_O_C.nc
2022-02-10 09:43:13 INFO [se.task:echo <99b7d264dc>] rmp_{{item[0]}}...
rmp_I_to_O_C.nc 
2022-02-10 09:43:13 INFO [se.task:echo <99b7d264dc>] rmp_{{item[0]}}...
rmp_N_to_O_T.nc
```

**Comment by uwefladrich** [comment]
Just to confirm that this is indeed not as expected.

For the record, here is a workaround, use list of dicts:
```yaml
base.echo:
  msg: "rmp_{{item.src}}_to_{{item.dst}}_{{item.mtd}}.nc"
loop:
  -
    src: IOCL
    dst: NOTM
    mtd: GAUSWGT
  -
    src: IOCL
    dst: NOUM
    mtd: GAUSWGT
  -
    src: IOCL
    dst: NOVM
    mtd: GAUSWGT
  -
    src: NOTM
    dst: IOCL
    mtd: GAUSWGT 
```
I will have a look at the issue as soon as I can.

**Comment by uwefladrich** [comment]
I realise there is another workaround, which is even shorter and, in my opinion, clearer:
```yaml
base.echo:
  msg: "rmp_{{src}}_to_{{dst}}_{{method}}.nc"
loop:
  with: [src, dst, method]
  in:
    - [IOCL, NOTM, GAUSWGT]
    - [IOCL, NOUM, GAUSWGT]
    - [IOCL, NOVM, GAUSWGT]
    - [NOTM, IOCL, GAUSWGT]
```
Basically ScriptEngine is tying a bit too hard to be smart in order to understand your first approach in the way you expect:

What happens is that the loop variables (`item` by default for lists, or `key`, `value` for dicts) are mapped to whatever the loop iterator provides. But it always expects a list of loop variables, even if it has length one. Extra loop variables or iterator items are ignored. This means that in your initial case, `item` is mapped to the first element of your list in each iteration. Since there is only one (implicit) loop variable, the rest of your list elements (e.g. `NOTM` and `GAUSWG` in the first iteration) are ignored. Since your are dealing with strings in your list, there is no problem indexing, so `item[0]` yields `I` and `item[1]` is `O` (from the string `IOCL` in the first iteration). So what you need to do is to provide your loop with enough variables to catch all elements in your lists in each iteration, meaning that you have to specify loop variables explicitly with `with`.

While this explains what is happening and also provides you with a (nice) way out of your issue, I do understand that it leaves room for surprises. Which is of course not good. The question is how to solve it. Should your initial script be dealt with as a special case? Which further implications would that have? Is documenting this particular case enough? I need to think a bit more about it.
