### ISSUE TITLE
base.getenv not returning context update

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#61]
```yaml
- do:
    - base.getenv:
        home: HOME
- base.echo:
    msg: "{{home}}"
```
Will not display the home directory because the context change from `base.getenv` inside the `do` job is not properly propagated back.
