### ISSUE TITLE
Cannot find eccodes library

### ISSUE THREAD

**Issue by JanStreffing** [uwefladrich/scriptengine#63]
Following the steps in 
https://ec-earth-4-tutorial.readthedocs.io/en/latest/preparations.html
and
https://ec-earth-4-tutorial.readthedocs.io/en/latest/building.html
I created a platform configuration for levante@dkrz.de and tried to run:
`se user-settings.yml platforms/levante-intel2022-openmpi.yml  compile-all.yml`

I am met with:

```
Traceback (most recent call last):
  File "/home/a/a270092/model_codes/.ECE4/bin/se", line 8, in <module>
    sys.exit(main())
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/scriptengine/cli/se.py", line 108, in main
    parsed_args = parse_cmd_line_args()
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/scriptengine/cli/se.py", line 51, in parse_cmd_line_args
    + ", ".join(load_tasks().keys()),
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/scriptengine/tasks/core/loader.py", line 21, in load
    loaded_tasks[ep.name] = ep.load()
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/a/a270092/model_codes/ocp-tool/ocp_tool/scriptengine_task.py", line 5, in <module>
    import ocp_tool.grib
  File "/home/a/a270092/model_codes/ocp-tool/ocp_tool/grib.py", line 3, in <module>
    import eccodes as ecc
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/eccodes/__init__.py", line 13, in <module>
    from .eccodes import *  # noqa
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/eccodes/eccodes.py", line 12, in <module>
    from gribapi import (
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/gribapi/__init__.py", line 13, in <module>
    from .gribapi import *  # noqa
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/gribapi/gribapi.py", line 34, in <module>
    from gribapi.errors import GribInternalError
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/gribapi/errors.py", line 16, in <module>
    from .bindings import ENC, ffi, lib
  File "/home/a/a270092/model_codes/.ECE4/lib/python3.9/site-packages/gribapi/bindings.py", line 35, in <module>
    raise RuntimeError("Cannot find the ecCodes library")
RuntimeError: Cannot find the ecCodes library
```

pip list shows that eccodes is installed:

```
pip list
Package                Version Editable project location
---------------------- ------- ------------------------------------
attrs                  22.1.0
cffi                   1.15.1
cftime                 1.6.2
deepdiff               5.8.1
deepmerge              1.0.1
eccodes                1.5.0
findlibs               0.0.2
Jinja2                 3.1.2
MarkupSafe             2.1.1
netCDF4                1.6.1
numpy                  1.23.3
ocp-tool               0.0.0   /home/a/a270092/model_codes/ocp-tool
ordered-set            4.1.0
pip                    22.2.2
pycparser              2.21
python-dateutil        2.8.2
PyYAML                 6.0
scriptengine           0.12.5
scriptengine-tasks-hpc 0.5.0
setuptools             58.1.0
six                    1.16.0
```
Any idea what went wrong? I also checked the ecCodes path given inside my platform config. That also seems to be the correct path though and i can find:

```
ls -lrt /work/ab0246/HPC_libraries/intel-oneapi-compilers/2022.0.1-gcc-11.2.0/openmpi/4.1.2-intel-2021.5.0/lib:
-rwxr-xr-x. 1 a270092 ab0246  9312912 Apr  6 13:35 libeccodes.so
-rwxr-xr-x. 1 a270092 ab0246   829416 Apr  6 13:35 libeccodes_f90.so
-rw-r--r--. 1 a270092 ab0246  1227604 Apr  6 13:35 libeccodes_f90.a
-rw-r--r--. 1 a270092 ab0246 18704622 Apr  6 13:35 libeccodes.a
.
.
.
```

My first try at a levante platform config:
```
# System-dependent configuration for EC-Earth 4 build on levante. Load a good set of default modules modules:
# module swap openmpi/4.1.2-intel-2021.5.0 intel-oneapi-compilers/2022.0.1-gcc-11.2.0 intel-oneapi-mkl/2022.0.1-gcc-11.2.0  git/2.31.1-gcc-11.2.0 cdo/2.0.5-gcc-11.2.0 nco/5.0.6-gcc-11.2.0 netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0 netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0 hdf5/1.12.1-openmpi-4.1.2-intel-2021.5.0  libaec/1.0.5-intel-2021.5.0

- base.context:

    build:

        lang:
            fortran:
                compiler: mpif90
            #   flags: -r8 -fp-model precise -align array32byte -O0 -check all,noarg_temp_created,bounds,uninit -ftrapuv -qopenmp -g -traceback -convert big_endian -march=core-avx2 -mtune=core-avx2
                flags: -r8 -fp-model precise -align array32byte -O3 -qopenmp -g -traceback -march=core-avx2 -mtune=core-avx2
                preprocessor: cpp

            c:
                compiler: mpicc
                flags: -g
                preprocessor: cpp

            linker:
                command: "{{build.lang.fortran.compiler}}"

            make:
                command: make

        libs:
            lapack:
                base_dir: /sw/spack-levante/openblas-0.3.18-mzclcq
                inc_dir: "{{build.libs.lapack.base_dir}}/include"
                lib_dir: "{{build.libs.lapack.base_dir}}/lib"
                libs: [openblas]

            grib:
                base_dir: /work/ab0246/HPC_libraries/intel-oneapi-compilers/2022.0.1-gcc-11.2.0/openmpi/4.1.2-intel-2021.5.0
                inc_dir: "{{build.libs.grib.base_dir}}/include"
                lib_dir: "{{build.libs.grib.base_dir}}/lib"
                libs: [eccodes_f90, eccodes]

            netcdf:
                base_dir: /sw/spack-levante/netcdf-c-4.8.1-2k3cmu
                inc_dir: "{{build.libs.netcdf.base_dir}}/include"
                lib_dir: "{{build.libs.netcdf.base_dir}}/lib"
                libs: [netcdff, netcdf]

            hdf5:
                base_dir: /sw/spack-levante/hdf5-1.12.1-tvymb5
                inc_dir: "{{build.libs.hdf5.base_dir}}/include"
                lib_dir: "{{build.libs.hdf5.base_dir}}/lib"
                libs: [hdf5_hl, hdf5, z]
        oifs:
            lang:
                fortran:
                    flags: -m64 -fconvert=big-endian
                    flags_fixed: -fdefault-real-8 -fdefault-double-8
                    macros: BLAS LITTLE LINUX INTEGER_IS_INT
                c:
                    macros: BLAS LITTLE LINUX INTEGER_IS_INT _ABI64
                linker:
                    flags: -ldl -lrt

```

**Comment by JanStreffing** [comment]
@uwefladrich

**Comment by uwefladrich** [comment]
I do not think that this is a ScriptEngine error. It seems to originate from the [uwefladrich/ocp-tool](https://github.com/uwefladrich/ocp-tool) and more specifically from the virtual environment setup in your case. Anyway, lets try to sort it out here, it it will be the same person over at uwefladrich/ocp-tool anyway :grin: 

I do not know _when_ in the build process you are getting the error but I suspect it is right at the beginning when you start the `se` command. In fact, I suspect that you would get the error when running `se --help` already?

**Comment by JanStreffing** [comment]
I do get the error with `se --help` already
I deleted .ECE4 and followed the guide again, this time skipping ocp-tools. Indeed se --help now works. So there is some problem with the ocp-tools part of https://ec-earth-4-tutorial.readthedocs.io/en/latest/preparations.html#creating-a-python-virtual-environment.

**Comment by uwefladrich** [comment]
Okay. I guess we could strip it further down to remove any trace of ScriptEngine and ocp-tool in the environment and still get the same error.

The thing is that `eccodes` is a bit of a difficult dependency. One (the major) issue is that ECMWF has stopped publishing packages on PyPI and only releases conda packages now. You can see that the newest PyPI eccodes package is version 1.5.0 (the one you load), while it is 2.27 on conda-forge. So I guess you would be out of luck with ECMWF support, they would probably refer to conda-forge.

While this does not on its own explains the error, issues like this have eventually convinced me to move to conda packages for EC-Earth. The setup has not completely settled yet, which is also the reason why the documentation is not updated.

You could try to create a conda environment instead, with something like

```yaml
name: ece-4

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.6
  - pip
  - eccodes
  - pip:
    - scriptengine
    - scriptengine-tasks-hpc

# Install from source dir for time being (pip -e):
# - ocp-tools
```
This is just an example, some adjustments could be needed. For example, you could specify an eccodes version, if you want it to match the version installed on the system. This depends a bit on the rest of the setup.

**Comment by JanStreffing** [comment]
Caused by not having a functioning library installed through pip.
Can be worked around be setting the $LD_LIBRARY_PATH to a functioning eccodes library manually.
Ultimately Uwe plans to move away from pip venvs. @uwefladrich feel free to close here unless you want to keep it open until a more permanent is set in place.

**Comment by uwefladrich** [comment]
I have, meanwhile, found a rather robust solution. It took me a while to understand the peculiarities of ecCodes installations and my conclusion is that there are, confusingly, two eccodes packages available, which provide the corresponding components:

* eccodes on [conda-forge](https://anaconda.org/conda-forge/eccodes) for the binary package
* eccodes on [PyPI](https://pypi.org/project/eccodes) for the Python API

The following conda env file will install both parts:

```yaml
#   conda env create -n <name> --file <this_file>.yml

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10  # or whatever
  - pip
  # The conda eccodes package delivers the binary library
  - eccodes
  - pip:
    # eccodes from PyPI delivers the Python bindings
    - eccodes
```

However, it is important to make sure that the installation does not interfere with any system-wide installation of ecCodes, i.e. make sure not to have loaded any other modules or environment variables pointing to system eccodes.

PS: There are, in fact, further ecCodes related packages. Conda-forge has also the [python-eccodes](https://anaconda.org/conda-forge/python-eccodes) package, which presumably provides the Python API. However, at the time of writing this package is at an older version than eccodes from PyPI, which is why we rely on the latter.
