### ISSUE TITLE
Support wildcards in file tasks

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#70]
For example,

```yaml
- base.copy
    src: foo/*.txt
    dst: bar/
```
for all base tasks where it makes sense.
