### ISSUE TITLE
base.find does not update context properly

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#74]
``base.find`` does not store result properly in jobs:
```yaml
- do:
    - base.find:
        path: foo
        pattern: bar
- base.echo:
    msg: "{{ result }}"
```
will write ``None``
