### ISSUE TITLE
Loops with empty or undefined specs

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#8]
Consider
```yaml
- echo:
    msg: "{{item}}"
  loop: "{{foo}}"
```
where `foo` is either undefined or an empty list. The loop body should not be executed.

Consider also the corner case
```yaml
- echo:
    msg: "{{item}}"
  loop:
```
i.e. the loop spec is YAML-null.
